name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Albertinesilva
          config_timezone: Europe/Minsk
          # config_display: columns  # display information in columns
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata # base content (user info)
          plugin_introduction: yes # general account information
          # plugin_sponsors: yes

          plugin_isocalendar: yes # 3D isometric calendar
          plugin_isocalendar_duration: full-year # displays activity for the full year

          plugin_languages: yes # display used programming languages
          plugin_languages_details: bytes-size, percentage # additional info (code size and percentage)

          plugin_achievements: yes

          plugin_achievements_threshold: X # (show locked achievements as well)
          plugin_achievements_display: detailed # detailed achievements info

          plugin_calendar: yes # displays yearly activity
          plugin_calendar_limit: 3 # show activity for the last 11 years

          plugin_habits: yes # daily and weekly activity
          plugin_habits_facts: yes # weekly activity analysis
          plugin_habits_charts: yes # activity charts

          plugin_licenses: yes # project license info
          plugin_licenses_setup: npm ci # detailed license info

          plugin_skyline: yes # 3D skyline activity plugin
          plugin_skyline_year: 2022 # selected year
          plugin_skyline_frames: 120 # number of frames
          plugin_skyline_quality: 1 # quality 1 = best

          # plugin_stargazers: yes # monthly star activity
          # plugin_stargazers_charts_type: chartist # activity chart type - smooth lines

          plugin_support: yes # support plugin

          plugin_topics: yes # used topics plugin
          plugin_topics_limit: 0
          plugin_topics_mode: icons